export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS';

export const SET_SINGER = 'SET_SINGER';

export const SET_PLAYLIST = 'SET_PLAYLIST';

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX';

export const SET_FULL_SCREEN = 'SET_FULL_SCREEN';
